// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtdtMdMMKp9AWEBh1MlQL16vIOqnS9Zdk',
    appId: '1:180800337352:web:8a95d1ff3023df1aac7cfd',
    messagingSenderId: '180800337352',
    projectId: 'memo-app-33071',
    authDomain: 'memo-app-33071.firebaseapp.com',
    storageBucket: 'memo-app-33071.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKbwmsB90Y6ld1kWbH4x3QuWzzbZyNSOw',
    appId: '1:180800337352:android:52841402db536a41ac7cfd',
    messagingSenderId: '180800337352',
    projectId: 'memo-app-33071',
    storageBucket: 'memo-app-33071.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBChlW4uoFYgY9i5GzXqUuuGRBVG6HfnnI',
    appId: '1:180800337352:ios:36ed6b5427674a6dac7cfd',
    messagingSenderId: '180800337352',
    projectId: 'memo-app-33071',
    storageBucket: 'memo-app-33071.firebasestorage.app',
    iosBundleId: 'com.suzukiaki.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBChlW4uoFYgY9i5GzXqUuuGRBVG6HfnnI',
    appId: '1:180800337352:ios:f7cac717dd6e36a0ac7cfd',
    messagingSenderId: '180800337352',
    projectId: 'memo-app-33071',
    storageBucket: 'memo-app-33071.firebasestorage.app',
    iosBundleId: 'com.suzukiaki.cleanTest2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtdtMdMMKp9AWEBh1MlQL16vIOqnS9Zdk',
    appId: '1:180800337352:web:d992c9e4d607348fac7cfd',
    messagingSenderId: '180800337352',
    projectId: 'memo-app-33071',
    authDomain: 'memo-app-33071.firebaseapp.com',
    storageBucket: 'memo-app-33071.firebasestorage.app',
  );
}
